tamagoyakii/minishell

includes/minishell.h
srcs/main.c

[Feat] 허용 헤더 추가 및 구조체 수정 #8

---

includes/execute.h
srcs/execute/child.c
srcs/execute/execute.c
srcs/execute/heredoc.c
srcs/execute/signal.c

- signal 함수 구현하기
- 히어독일 때
- SIGINT : exit (1);
- SIGQUIT : 무시
- 자식 프로세스일 때
- SIGINT : "^C" 출력
- SIGQUIT : ^\Quit: 3" 출력
- exit (시그널넘버 + 128);

[Feat/execute] signal 함수 구현 close #10

---

includes/execute.h
includes/minishell.h
srcs/execute/child.c
srcs/execute/execute.c
srcs/execute/frees.c
srcs/execute/init_execute.c
srcs/execute/pipe.c
srcs/execute/redir.c
srcs/execute/util_execute.c

-ft_malloc구현, t_pipe 제거 
- ft_malloc구현 -> malloc 전부 대체
- t_pipe 제거에 따라 파일 수정
- 각종 널가드 추가

[Fix/execute]ft_malloc구현, t_pipe 제거 close #18

---

includes/execute.h
includes/minishell.h
srcs/execute/builtin.c
srcs/execute/builtin_echo.c
srcs/execute/builtin_exit.c
srcs/execute/execute.c
srcs/execute/heredoc.c
srcs/execute/path.c
srcs/execute/redir.c
srcs/execute/util_execute.c

- exit, echo, error처리 구현
- 빌트인 구현
- echo
- exit
- too many arguments, numeric argument 순으로 처리
- 에러 처리 구현
- 오픈 실패시 리턴값 받아서 처리하도록 수정
- 빌트인 프로세스에서 그냥 리턴시켜주면 되버리네요?? 리턴값 없어도 될듯

[Feat/execute] exit, echo, error처리 구현 close #25

---

srcs/execute/builtin_echo.c
srcs/execute/child.c

- wait 이상하게 하던거 수정 및 echo exit status 변경
- wait 프로세스 개수 -1만큼 하던거 수정
- ft_echo 종료시 exit status 0으로 변경

[Fix] wait 이상하게 하던거 수정 및 echo exit status 변경

---

includes/execute.h
srcs/execute/builtin_cd.c
srcs/execute/builtin_env.c
srcs/execute/builtin_pwd.c
srcs/execute/path.c
srcs/execute/util_env.c

- pwd, env, cd 빌트인 함수 구현
- pwd, env, cd 빌트인 함수 구현
- env value 찾는 함수 env 찾는 함수로 수정

[Feat] pwd, env, cd 빌트인 함수 구현 #30

---

includes/execute.h
srcs/execute/builtin_cd.c
srcs/execute/builtin_env.c
srcs/execute/builtin_export.c
srcs/execute/builtin_unset.c
srcs/execute/util_env.c
srcs/execute/util_env2.c

- unset, export 구현
- 구현했던 함수 수정
- cd : pwd가 NULL일 경우 빈문자열 넣어주기
- env : 마지막 리스트 안 읽는 오류 수정
- unset, export 구현
- 환경변수 관련 유틸 함수 추가 : ‼️놈 맞추기, 리팩토링 필요
```c
t_env	*get_env(char *key); // 해당하는 key가 있는 env 리스트 반환
int	is_valid_key(char *key); // 환경변수 등록시 유효한 key인지 검사
void	print_invalid_error(char *cmd, char *input); // unset, export 유효하지 않을 경우 오류 출력
void	update_2_arr_env(void); // 기존의 환경변수 이중배열 프리하고 새롭게 이중배열 만들어줌
void	make_2_arr_env(void); // 환경변수 연결리스트를 이중배열로 만들어줌
void	insert_new_env(t_env **lst, t_env *tmp, t_env *new, char *env); // 새로운 환경변수 리스트를 정렬해서 넣어줌
t_env	*new_env_lst(char *env); // 새로운 환경변수 리스트 생성
void	add_one(t_env **lst, char *env); // 환경변수 추가하는 함수
void	set_env(char **env); // init 처음 시작시 전역변수 env 셋팅
```

[Feat] unset, export 구현 #30

---

srcs/execute/child.c
srcs/execute/execute.c
srcs/execute/heredoc.c

- execve_process 에러 처리 부분 수정
- heredoc 실패시 exit status 설정해주기
- execute.c init 실패시 pipe close해주는 코드 추가

[Fix/execute] 에러처리 보완

---

srcs/execute/builtin_export.c
srcs/execute/builtin_pwd.c
srcs/execute/builtin_unset.c
srcs/execute/util_env.c

- 자잘한 에러 수정
- FALSE 수정하기(False -> FALSE)
- make_new_env 삭제
- export, unset valid key 아닐 경우 에러 메시지 수정
- pwd 개행 추가

[Fix/execute] 오타 수정

---

Makefile
includes/execute.h
includes/minishell.h
includes/utils.h
main_execute.c
srcs/execute/builtin.c
srcs/execute/builtin_export.c
srcs/execute/heredoc.c
srcs/execute/run_fork.c
srcs/utils/env1.c
srcs/utils/env2.c
srcs/utils/frees.c
srcs/utils/global.c
srcs/utils/signal.c

- Makefile 생성 및 make 되도록 수정
- 안쓰는 변수 제거
- 오타 다수 수정

[Feat/Refactor] Makefile 생성 및 make 되도록 수정

---

main_execute.c
srcs/execute/builtin_export.c
srcs/utils/env2.c
srcs/utils/frees.c

- export 주소 잘못 옮긴거 롤백
- 한줄짜리 괄호 삭제

[Fix] export 주소 잘못 옮긴거 롤백

---

Makefile
includes/parse.h
srcs/main.c
srcs/parse/create_argvs.c
srcs/parse/create_argvs_2.c
srcs/parse/parse.c
srcs/parse/split_dummy.c
srcs/parse/utils_env.c

- 구현부와 테스트하기 위해 전체 소스를 리팩토링 하였습니다. 
- _`Makefile`_
- 빌드 가능하도록 수정하였습니다. (파싱부 + 구현부)
- _`main.c`_ 
- 빌드 후 파싱부와 구현부 실행가능하도록 수정하였습니다.
- _`parse.c`_  _`parse.h`_ _`create_argvs_1,2.c`_
- syntax 에러 업데이트 후, 컴파일되지 않는 부분을 수정했습니다.
- _`split_dummy.c`_
- `'echo 1234'` -> `'echo ', '1234'` 공백포함 이슈
- 공백 처리과정에서 공백이 포함되는 이슈를 해결했습니다.
- _`utils_env.c`_
- 헤더파일 경로를 수정했습니다.
- 사용되지 않는 함수를 제거했습니다.

[Refactor] 구현부 연결 및 빌드 #54

---

srcs/parse/create_argvs_2.c

- redir 처리 시 커맨드 저장 안되는 이슈 해결했습니다.
- token이 redir가 아닐 경우 type->redir를 NONE으로 처리

[Feat] token이 redir가 아닐 경우 type->redir를 NONE으로 처리 Close #59

---

srcs/execute/builtin_exit.c
srcs/execute/builtin_export.c
srcs/execute/builtin_unset.c
srcs/execute/init_execute.c
srcs/execute/open.c
srcs/utils/frees.c

- builtin 실행 오류 수정
- pipe 0인 경우 cnt_pipe 초기화 문제 수정
- exit만 들어왔을 경우 세그폴트 나는부분 수정
- free_argv에서 heredoc 프리해주는 부분 추가
- unset++ 잘못한거 수정
- ft_open single_builtin인 경우 에러 메시지 출력 안하던거 출력하도록 수정

[Fix] builtin 실행 오류 수정

---

includes/parse.h
srcs/parse/create_argvs.c

- 아침에 빌드를 해보니 처리가 덜 되어있었다! 쏘리
- _`create_argvs.c`_
- cmd의 내용이 argvs에 저장되도록 수정 
- _`parse.h`_
-  parse구조체 정의 시, `t_cmd` `t_type`를 찾지못하는 부분 수정
-

[Fix] 빌드되지 않는 부분 수정  #62

---

srcs/execute/builtin_cd.c

- 느낌표 없어서 뜨는 말록 에러 수정
- 느낌표 없어서 뜨는 말록 에러 수정
피알 전에 테스트 꼭 여러번 돌려보겠씀다

[Fix] 느낌표 없어서 뜨는 말록 에러 수정

---

.gitignore
srcs/parse/create_argvs_2.c
srcs/parse/parse.c

- `argv` 파싱 오류 해결
- `add_redir`, `add_word`할 때 마지막 argv의 주소를 보내도록 수정했습니다.

[Fix] argv 파싱 오류 해결 #55

---

srcs/parse/create_argvs.c
srcs/parse/create_argvs_2.c

- cmdNull 처리
- _`create_argvs_2.c`_ _`create_argvs.c`_
- 명령어가 없을 경우, 분기문을 추가하여 cmd가 NULL 유지할 수 있도록 수정
-

[Fix] 명령어가 없을 경우 cmd null 저장 close #68

---

srcs/parse/split_line.c

- split_line() free 문제
- free가 되지않는 부분을 수정하였습니다.
-

[Fix] leaks 처리 #70

---

srcs/execute/path.c
srcs/execute/run_fork.c

- cdm 널인 경우, excve(디렉토리)인 경우 에러 처리
- cmd 널인 경우 자식 프로세스 정상 종료 처리
- excve(디렉토리)인 경우 에러 처리
참고 -> https://mymanual.tistory.com/2

[Fix] cmd 널인 경우, excve(디렉토리)인 경우 에러 처리

---

includes/global.h
srcs/parse/create_argvs_2.c
srcs/parse/parse.c

- leaks 누수 부분 수정
- _`parse.c`_ _`create_argvs_2.c`_ 
- leak이 발생하는 부분을 수정하였습니다.
- _`global.h`_ 
- parse 구조체도 수정하였습니다.
- _`parse.c`_
- free 로직구조를 변경하였습니다.

[Fix] leaks 이슈 해결 #75

---

srcs/execute/builtin_cd.c
srcs/execute/path.c
srcs/main.c

- cd, path, main error 발생시 오류 메시지 수정 
- cd 이동 실패시 오류 메시지 cmd 추가
- path 찾을 때 환경변수 PATH 없을 때, 오류메시지 "No such file or directory" 추가
- 메인에서 인자 1개 이상일 때 실행 안되게 하기

[Fix] cd, path, main error 발생시 오류 메시지 수정 

---

srcs/execute/path.c

- "./"없이 파일이 실행되던 문제 해결
- path 찾다가 "/" 있으면 무조건 해당 절대/상대경로로 실행.
- "/" 없으면 PATH에서 찾아서 실행

[Fix] ./없이 파일이 실행되던 문제 해결 close #84

---

Makefile

- Makefile 예쁘게 만들기
- make 할 때마다 출력되던 거 막기
- 물 기름 비누는 주석 삭제하면 됩니다

[Fix] Makefile 예쁘게 만들기

---

srcs/parse/split_dummy.c

-  `< < a` heredoc으로 인식되는 이슈 해결
- _`split_dummy.c`_
- 연속된 리다이렉션이(< <) 올 경우 두 문자를 하나로 합치는 부분(<<)을 수정 
-

[Fix] '< < a' heredoc으로 인식되는 이슈 해결 close #88

---

srcs/parse/create_argvs_2.c

- pipe Leak 해결
- 원인 : 할당된 파이프 문자('|')가 free되지 않음
- _`create_argvs_2.c`_
- 할당된 파이프 문자('|') free될 수 있도록 소스 추가하였습니다.

[Fix] pipe Leak 수정 #79

---

includes/global.h
includes/parse.h
srcs/parse/create_argvs.c
srcs/parse/create_tokens.c
srcs/parse/parse.c
srcs/parse/split_line.c

-
- `t_parse` 구조체에 `dummys`를 추가했습니다.
- `replace.c`를 제외한 `parse` 폴더의 파일들에 norm을 맞추었습니다. -> **`replace.c` 파일 norm 확인해주세요!!**
-  `parse()` 함수 리팩토링에 따라 `free()` 하는 부분들을 옮겼습니다.
-  이에 따른 2개의 leaks가 발생했습니다.... 다들 함께 찾아주세요...

[Refactor] parse() 함수 리팩토링 #94

---

srcs/parse/create_argvs.c
srcs/parse/create_argvs_2.c
srcs/parse/split_line.c

- *seek 넣어서 leaks 해결
- `split_line()` 함수와 `create_tokens()` 함수에 `*seek` 변수를 추가하여 메모리 누수 처리하였습니다.

[Fix] *seek 넣어서 leaks 해결 Close #98

---

srcs/parse/split_line.c

- split_line 리팩토링
- _`split_line.c`_
- 리팩토링 진행했습니다.

[Refactor] split_line 리팩토링 Close #100

---

Makefile
includes/utils.h
srcs/execute/heredoc.c
srcs/execute/run_fork.c
srcs/main.c
srcs/parse/parse.c
srcs/utils/signal.c

- 메인, 자식 프로세스 및 히어독 signal 고치기
- 시그널 처리가 안돌아가던 이유가 위치&리드라인 때문 => 위치 이동&리드라인 설치 
- 시그널 처리에서 `rl_replace_line` 쓰기 위해 realine을 설치 : `brew install readline`해주세요
- 그리고 안돌아가서 리드라인 관련 헤더 넣기위해 파싱 파일 수정
- 메이크파일도 수정
- 미니쉘 안의 미니쉘에서 시그널 처리는 추가해보겠습니다....

[Fix] 메인, 자식 프로세스 및 히어독 signal 고치기 #78

---

srcs/execute/path.c

-  '.', '..' 들어왔을 때 에러처리
-  path 검사시 맨 처음에 검사해줘서 처리

[Fix] '.', '..' 들어왔을 때 에러처리 close #96

---

srcs/utils/env2.c

-  SHLVL 변경코드 추가
- minishell 실행시 SHLVL 찾아서 1 증가시켜주기
- SHLVL 없다면 1로 만들어주기

[Feat] SHLVL 변경코드 추가 close #104

---

srcs/main.c
srcs/parse/create_tokens.c

- token 변수 이름 수정 및 norm 검사
- token에 head로 사용하던 변수 이름 수정했습니다.
- 파싱폴더와 main.c 파일 모두 norm 확인했습니다.

[Refactor] token 변수 이름 수정 및 norm 검사 #108

---

includes/parse.h
srcs/parse/replace_env.c

[Refactor] get_value 지역함수로 선언 #108

---

srcs/parse/parse.c

- 화이트 스페이스 처리
- _`parse.c`_
- 화이트 스페이스 처리 로직을 추가하였습니다.

[Feat] 화이트 스페이스 처리 Close #113

---

includes/parse.h
srcs/execute/execute.c
srcs/execute/hdoc.c
srcs/execute/heredoc.c
srcs/execute/path.c
srcs/parse/replace_env.c
srcs/parse/replace_env_2.c
srcs/utils/signal.c

- heredoc 환경변수 치환 
- heredoc에서 환경변수 입력시 치환해주도록 수정
- $로 시작하는 경우 $ 다음 문자가 key가 될 수 없으면 $ 무시. "", '' 안에 $ 들어갈 경우는 살리도록 수정

[Fix] heredoc 환경변수 치환 close #115

---

includes/execute.h
includes/parse.h
includes/utils.h

-heredoc 환경변수에 따른 헤더 변경
-heredoc 환경변수에 따른 헤더 변경

[Fix] heredoc 환경변수에 따른 헤더 변경

---

Makefile
includes/utils.h
srcs/execute/hdoc.c
srcs/execute/run_fork.c
srcs/main.c
srcs/utils/signal.c

- 시그널 프엪 씹힌 현상 수정
- 어제는 되던 시그널이 오늘안 안먹네요. 히어독에서 포크 전에 IGN를 안해도 잘 작동했는데 경우에 따라 다른 것 같습니다.
- 
-

[Fix] 시그널 프엪 씹힌 현상 수정 #120

---

includes/utils.h

- 추가 된 두 파일 utils.h 에 놈 검사 및 수정
- 
- utils.h 의 추가 된 두 함수 norm 검사 및 수정

Fix/util norm check#122

---

srcs/parse/split_dummy.c

- 파이프 입력시, 빈문자열이 입력되는 부분 해결
- _`split_dummy.c`_
- 화이트스페이스에 대한 파이프 처리 부분을 수정하였습니다.

[Fix] 화이트스페이스 처리에 대한 이슈 해결 #125

---

srcs/parse/replace_env_2.c

- 화이트스페이스 $ 읽을때 반영하도록 수정
- 화이트스페이스 $ 읽을때 반영하도록 수정

[Fix]화이트스페이스 $ 읽을때 반영하도록 수정

---

srcs/execute/execute.c
srcs/main.c

- 히어독일 때 시그널 표시되는 문제 수정
- set 터미널 설정을 히어독 처리 이후로 이동시켰습니다.

[Fix] 히어독일 때 시그널 표시되는 문제 수정

---

srcs/execute/builtin.c
srcs/execute/builtin_echo.c
srcs/execute/builtin_export.c
srcs/execute/builtin_unset.c
srcs/parse/parse.c
srcs/utils/env1.c

- 빌트인 종료 코드 수정 및 에러메시지 수정
-  export, unset 에러 메시지 변경
- 파싱 syntax error 메시지 수정
- 빌트인 함수 종료 코드 추가 및 위치 이동

[Fix] 빌트인 종료 코드 수정 및 에러메시지 수정

---

includes/execute.h
srcs/execute/execute.c
srcs/execute/init_execute.c
srcs/execute/pipe.c
srcs/execute/run_fork.c

- pipe 에러시 파이프 정상적으로 닫도록 수정
- close_pipe 함수가 cnt를 받도록 수정

[Fix] pipe 에러시 파이프 정상적으로 닫도록 수정

---

srcs/execute/builtin.c
srcs/execute/builtin_exit.c
srcs/parse/replace_env.c

- 환경변수 오류 수정, exit code 수정
- 환경변수 치환 시 size 잘못 세던거 변경
- exit 뒤에 뭐 없을 때 last_exit_number로 종료하도록 수정
- single builtin시 redirect out부터 처리하도록 수정

[Fix] 환경변수 오류 수정, exit code 수정

---

srcs/utils/env2.c

- 환경변수 init 코드 수정
- 헤드를 전역변수에 안넣어줬더니 환경변수 애가 중간부터만 들고있음...
- 헤드를 전역변수에 넣어줘서 해결

[Fix]환경변수 init 코드 수정 #138

---

srcs/parse/create_dummies.c

- `echo "C"|` -> `C|`로 출력되는 이슈
-  쿼터 처리 후 다음에 리다이렉션 및 파이프가 올 경우 type이 변경되도록 수정하였습니다.

[Fix] 쿼터 처리 후, 파이프가 Word로 인식되는 부분 해결 Close #142

---

srcs/execute/hdoc.c
srcs/parse/create_argvs_2.c

- hdoc 빈문자열 처리
- hdoc 디렉토리를 `/tmp/.0` 으로 수정했습니다.
- syntax error 중복 처리하고 있는 부분 삭제했습니다.

[Fix] hdoc 빈문자열 처리 #146

---

srcs/parse/parse.c

[Fix] wspace만 들어올 경우 leaks 처리 Close #148

---

srcs/execute/builtin_echo.c
srcs/parse/replace_env.c

- echo 옵션 인식 에러 수정, 환경변수 value  Null일 경우 에러 수정
- echo 옵션 인식 에러 수정, 환경변수 value  Null일 경우 에러 수정

[Fix] env_error close #152
